name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Download the source code
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with MPLAB 6.00 and XC8 2.31
        uses: dsatsangi/mplab-xc8-build-action@debug
        with:
          project: Blink128a.X
          configuration: default
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}